Chart.yamlapiVersion: v2
name: .
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: dex
  version: "0.12.1"
  repository: "https://charts.dexidp.io"
- name: jumpserver
  version: "2.28.4"
  repository: "https://jumpserver.github.io/helm-charts"
- name: openldap
  version: "2.0.4"
  repository: "https://jp-gouin.github.io/helm-openldap/"
- name: gitlab
  version: "6.6.2"
  repository: "https://charts.gitlab.io/"
- name: harbor
  version: "1.10.2"
  repository: "https://helm.goharbor.io"
- name: fluxcd2
  version: "2.2.0"
  repository: "https://fluxcd-community.github.io/helm-charts"
- name: velero
  version: "2.32.4"
  repository: "https://helm.goharbor.io"
- name: kube2iam
  version: "3.0.0"
  repository: "file://charts/kube2iam"
